# Generated by Django 3.2.7 on 2021-11-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='First and second name')),
                ('customer_phone', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('category', models.CharField(choices=[('cottege', 'Cottage'), ('apartment', 'Apartment')], max_length=15)),
                ('body', models.TextField(verbose_name='Customer whishes')),
            ],
        ),
    ]
