# Generated by Django 3.2.7 on 2021-11-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vallox_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_surname',
            field=models.CharField(default='', max_length=100, verbose_name='Second name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
    ]
