# Generated by Django 3.2.7 on 2021-11-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vallox_form', '0002_auto_20211118_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
